import type { ShopItemDefinition } from '../types/game'

export const GAME_CONFIG = {
  title: 'ちる子満足計画',
  saveKey: 'chiruko-satisfaction-save-v1',
  saveVersion: 8,
  autoSaveIntervalMs: 5_000,
  productionTickMs: 100,
  maxOfflineSeconds: 8 * 60 * 60,
  achievementProductionBonus: 0.01,
  virtueMarkBonusPerDoubling: 0.1,
  prestigeBaseRequirement: 500_000_000,
  luckyEvent: {
    firstDelayMinMs: 18_000,
    firstDelayMaxMs: 34_000,
    repeatDelayMinMs: 45_000,
    repeatDelayMaxMs: 90_000,
    visibleMs: 13_000,
    comboAssistMinActiveBuffs: 2,
    comboAssistDelayMinMs: 3_000,
    comboAssistDelayMaxMs: 6_000,
    comboAssistBuffChance: 0.65,
    // Two active blessings can help once, but must not create a self-feeding loop.
    comboAssistUsesPerBuffWindow: 1,
    maxConcurrentBuffs: 3,
  },
  anomalyDetection: {
    luckyWindowMs: 30_000,
    // A chain legitimately fires three follow-up events about 900 ms apart.
    // Keep enough room for that chain, while rejecting automation that clicks
    // the same event over and over in a short window.
    maxLuckyEventsPerWindow: 8,
    minLuckyClaimIntervalMs: 650,
    // The longest normal lucky reward is a 5x chain step. This margin also
    // leaves room for rounding and seasonal bonuses.
    maxLuckyRewardMultiplier: 6,
    maxGainRateMultiplier: 420,
  },
  characterImages: {
    main: '/assets/characters/chiruko-sit.png',
    smile: '/assets/characters/chiruko-smile.png',
    nikoniko: '/assets/characters/chiruko-nikoniko.png',
    sleep: '/assets/characters/chiruko-sleep.png',
    read: '/assets/characters/chiruko-read-transparent.png',
    run: '/assets/characters/chiruko-run.png',
  },
} as const

// 商品を増やすときは、この配列へ1項目追加するだけでショップに表示されます。
// imagePath を省略すると icon の文字が仮アイコンとして表示されます。
export const SHOP_ITEMS: ShopItemDefinition[] = [
  {
    id: 'petting',
    name: 'なでなで',
    description: '教祖のごきげんを直接底上げする、基本にして至高の行い。',
    baseCost: 15,
    costGrowth: 1.15,
    effectType: 'click',
    effectValue: 1,
    icon: '♡',
    imagePath: '/assets/items/petting.png',
  },
  {
    id: 'sweet-treat',
    name: 'あまいおやつ',
    description: 'ヤンヤンつけボー的な聖菓。少しずつ満足を生む。',
    baseCost: 35,
    costGrowth: 1.15,
    effectType: 'perSecond',
    effectValue: 0.5,
    icon: '♢',
    imagePath: '/assets/items/sweet-treat.png',
  },
  {
    id: 'soft-futon',
    name: 'ふかふかおふとん',
    description: 'よく眠れた朝も救済の欠片。安心感が満足を育てる。',
    baseCost: 180,
    costGrowth: 1.15,
    effectType: 'perSecond',
    effectValue: 3,
    icon: '☁',
    imagePath: '/assets/items/soft-futon.png',
  },
  {
    id: 'chiruko-doll',
    name: 'ちる子ちゃん人形',
    description: '本人監修（ということになっている）ありがたい人形。',
    baseCost: 1_100,
    costGrowth: 1.15,
    effectType: 'perSecond',
    effectValue: 14,
    icon: '♙',
    imagePath: '/assets/items/chiruko-doll.png',
  },
  {
    id: 'desktop-accessory',
    name: 'デスクトップアクセサリ',
    description: 'PCのすみでこつこつ働く、小さな満足生産所。',
    baseCost: 14_400,
    costGrowth: 1.15,
    effectType: 'perSecond',
    effectValue: 65,
    icon: '▣',
    imagePath: '/assets/items/desktop-accessory.png',
  },
  {
    id: 'sora-2',
    name: 'Sora2',
    description: 'かつてOpenAIが提供した動画・音声生成モデル。物理表現と同期音声で、布教記録を勝手に映画化する。',
    baseCost: 84_000,
    costGrowth: 1.15,
    effectType: 'perSecond',
    effectValue: 350,
    icon: 'S2',
    imagePath: '/assets/items/sora-2.png',
  },
  {
    id: 'believer',
    name: '満足教の信者',
    description: '満足を信じ、満足を広め、ついでに満足を生産する。',
    baseCost: 1_250_000,
    costGrowth: 1.15,
    effectType: 'perSecond',
    effectValue: 2_000,
    icon: '♟',
    imagePath: '/assets/items/believer.png',
  },
  {
    id: 'altar',
    name: '満足教の祭壇',
    description: '日々の祈りを大きな満足へ変換する荘厳な設備。',
    baseCost: 8_000_000,
    costGrowth: 1.15,
    effectType: 'perSecond',
    effectValue: 12_000,
    icon: '✦',
    imagePath: '/assets/items/altar.png',
  },
  {
    id: 'giant-statue',
    name: '巨大ちる子像',
    description: '見上げれば、そこに満足がある。再布教前の大きな到達点。',
    baseCost: 120_000_000,
    costGrowth: 1.15,
    effectType: 'perSecond',
    effectValue: 85_000,
    icon: '♛',
    imagePath: '/assets/items/giant-statue.png',
  },
  {
    id: 'ramen-sanctum',
    name: '深夜のラーメン聖堂',
    description: '湯気と背徳感を満足へ変える、深夜限定ではない聖堂。',
    baseCost: 900_000_000,
    costGrowth: 1.15,
    effectType: 'perSecond',
    effectValue: 600_000,
    icon: '麺',
    imagePath: '/assets/items/ramen-sanctum.png',
  },
  {
    id: 'cult-broadcast',
    name: '満足教広報局',
    description: '教義が決まる前から放送だけは24時間続いている。',
    baseCost: 18_000_000_000,
    costGrowth: 1.15,
    effectType: 'perSecond',
    effectValue: 4_500_000,
    icon: '報',
    imagePath: '/assets/items/cult-broadcast.png',
  },
  {
    id: 'neo-cathedral',
    name: 'ネオサイタマ大聖堂',
    description: '黒と金で統一された、所在地非公開の巨大布教拠点。',
    baseCost: 150_000_000_000,
    costGrowth: 1.15,
    effectType: 'perSecond',
    effectValue: 35_000_000,
    icon: '堂',
    imagePath: '/assets/items/neo-cathedral.png',
  },
  {
    id: 'dimension-gate',
    name: '満足次元ゲート',
    description: 'まだ満たされていない世界へ勝手に満足を送り込む。',
    baseCost: 2_600_000_000_000,
    costGrowth: 1.15,
    effectType: 'perSecond',
    effectValue: 290_000_000,
    icon: '門',
    imagePath: '/assets/items/dimension-gate.png',
  },
  {
    id: 'cosmic-chiruko',
    name: '宇宙ちる子布教船',
    description: '満足を載せ、教義未定のまま銀河の彼方へ出航する。',
    baseCost: 24_000_000_000_000,
    costGrowth: 1.15,
    effectType: 'perSecond',
    effectValue: 2_500_000_000,
    icon: '宙',
    imagePath: '/assets/items/cosmic-chiruko.png',
  },
  {
    id: 'sora-3',
    name: 'Sora3',
    description: 'Sora2の先を満足教が勝手に想像した架空の進化版。映像だけでなく、銀河規模の布教世界まで生成する。',
    baseCost: 480_000_000_000_000,
    costGrowth: 1.15,
    effectType: 'perSecond',
    effectValue: 23_000_000_000,
    icon: 'S3',
    imagePath: '/assets/items/sora-3.png',
  },
  {
    id: 'satisfaction-observatory',
    name: '満足天文台',
    description: '満足の星を観測し、まだ見ぬ信者へ光を送る施設。',
    baseCost: 5_000_000_000_000_000,
    costGrowth: 1.15,
    effectType: 'perSecond',
    effectValue: 100_000_000_000_000,
    icon: '天',
    imagePath: '/assets/items/satisfaction-observatory.png',
  },
  {
    id: 'galaxy-mission-fleet',
    name: '銀河布教艦隊',
    description: '満足を積んだ船団が、銀河のすみずみまで教義を届ける。',
    baseCost: 2_000_000_000_000_000_000,
    costGrowth: 1.15,
    effectType: 'perSecond',
    effectValue: 500_000_000_000_000,
    icon: '艦',
    imagePath: '/assets/items/galaxy-mission-fleet.png',
  },
  {
    id: 'satisfaction-simulator',
    name: '満足宇宙シミュレータ',
    description: '宇宙全体を満足で満たすための演算施設。計算が終わる前に、次の宇宙が始まる。',
    baseCost: 400_000_000_000_000_000_000,
    costGrowth: 1.15,
    effectType: 'perSecond',
    effectValue: 3_000_000_000_000_000,
    icon: '宇',
    imagePath: '/assets/items/satisfaction-simulator.png',
  },
  {
    id: 'sora-4',
    name: 'Sora4',
    description: 'Sora3の先にある、まだ名前のない映像世界。想像した満足を、そのまま現実へ出力する。',
    baseCost: 100_000_000_000_000_000_000_000,
    costGrowth: 1.15,
    effectType: 'perSecond',
    effectValue: 20_000_000_000_000_000,
    icon: 'S4',
    imagePath: '/assets/items/sora-4.png',
  },
]
