import { assetPath } from '../utils/assetPath'

/** Generated from docs/dialogue-voice-manifest.csv. */
export const VOICE_CLIP_PATHS: Record<string, string> = {
  "今日の小さな満足に、感謝いたしましょう。": "/assets/audio/voice/dialogue-base-01.mp3",
  "ごきげんよう。本日もほどほどに満たされてまいりましょう。": "/assets/audio/voice/dialogue-base-02.mp3",
  "満足は逃げませんわ。たぶん。ですので、焦らずどうぞ。": "/assets/audio/voice/dialogue-base-03.mp3",
  "教義は簡単ですの。嬉しかったら、それが満足ですわ。": "/assets/audio/voice/dialogue-base-04.mp3",
  "数字が増える様子は、いつ見てもよいものですわね。": "/assets/audio/voice/dialogue-base-05.mp3",
  "わたくしを眺める時間も、立派な活動記録ですのよ。": "/assets/audio/voice/dialogue-base-06.mp3",
  "今日も世界のすみっこから、静かに布教中ですわ。": "/assets/audio/voice/dialogue-base-07.mp3",
  "難しいことは明日のわたくしに任せましょう。": "/assets/audio/voice/dialogue-base-08.mp3",
  "休憩もまた満足。異論は認めますけれど、聞き流しますわ。": "/assets/audio/voice/dialogue-base-09.mp3",
  "満たされておりますか？ まだなら、もうひとさわりどうぞ。": "/assets/audio/voice/dialogue-base-10.mp3",
  "大丈夫ですわ。だいたいのことは、おやつと睡眠で整います。": "/assets/audio/voice/dialogue-base-11.mp3",
  "その熱意、救済印を押して差し上げたいくらいですわ。": "/assets/audio/voice/dialogue-base-12.mp3",
  "夜更かしの信者には、あたたかい飲み物を推奨いたしますわ。": "/assets/audio/voice/dialogue-time-late-night-01.mp3",
  "深夜の満足は、昼より少しだけ秘密めいておりますの。": "/assets/audio/voice/dialogue-time-late-night-02.mp3",
  "眠れない夜ですの？ では、静かに数字を増やしましょう。": "/assets/audio/voice/dialogue-time-late-night-03.mp3",
  "おはようございます。朝の満足を一杯どうぞ。": "/assets/audio/voice/dialogue-time-morning-01.mp3",
  "起きられただけで、本日はすでに一徳ですわ。": "/assets/audio/voice/dialogue-time-morning-02.mp3",
  "朝一番のひとさわり、確かに受け取りました。": "/assets/audio/voice/dialogue-time-morning-03.mp3",
  "お昼の布教活動、お疲れさまですわ。": "/assets/audio/voice/dialogue-time-daytime-01.mp3",
  "日の高いうちから熱心ですこと。よい心がけですわ。": "/assets/audio/voice/dialogue-time-daytime-02.mp3",
  "おやつの時間まで、満足を貯めておきましょう。": "/assets/audio/voice/dialogue-time-daytime-03.mp3",
  "本日も一日、お疲れさまでした。ここではゆるりとどうぞ。": "/assets/audio/voice/dialogue-time-evening-01.mp3",
  "夕暮れは、増えた数字を眺めるのによい時間ですわね。": "/assets/audio/voice/dialogue-time-evening-02.mp3",
  "そろそろ、ふかふかおふとんの御利益が恋しい頃ですわ。": "/assets/audio/voice/dialogue-time-evening-03.mp3",
  "おでこは出ておりますけれど、丁重にお願いいたしますわ。": "/assets/audio/voice/dialogue-facility-petting-01.mp3",
  "なでなでは回数より心ですの。回数も嬉しいですけれど。": "/assets/audio/voice/dialogue-facility-petting-02.mp3",
  "あまいおやつは、教義よりも人をまとめる力がありますわ。": "/assets/audio/voice/dialogue-facility-sweet-treat-01.mp3",
  "糖分による救済は、たいへん即効性がございます。": "/assets/audio/voice/dialogue-facility-sweet-treat-02.mp3",
  "ふかふかのおふとんこそ、文明がたどり着いた答えですわ。": "/assets/audio/voice/dialogue-facility-soft-futon-01.mp3",
  "あと五分だけ……という祈りは、世界共通ですのね。": "/assets/audio/voice/dialogue-facility-soft-futon-02.mp3",
  "人形のわたくしも、ちゃんとおでこが見えておりますわね。": "/assets/audio/voice/dialogue-facility-chiruko-doll-01.mp3",
  "ちる子ちゃん人形は、本人監修ということになっております。": "/assets/audio/voice/dialogue-facility-chiruko-doll-02.mp3",
  "PCのすみは落ち着きますわ。邪魔にならない程度に働きます。": "/assets/audio/voice/dialogue-facility-desktop-accessory-01.mp3",
  "閉じないでいただければ、こつこつ満たしておきますわ。": "/assets/audio/voice/dialogue-facility-desktop-accessory-02.mp3",
  "この布教活動、映像と音声で記録しておきましょう。": "/assets/audio/voice/dialogue-facility-sora-2-01.mp3",
  "想像した景色が動き出すなんて、よい時代ですわね。": "/assets/audio/voice/dialogue-facility-sora-2-02.mp3",
  "信者が増えましたわ。教義は……追って決めましょう。": "/assets/audio/voice/dialogue-facility-believer-01.mp3",
  "入信は自由、退会も自由。満足だけ持ち帰ってくださいませ。": "/assets/audio/voice/dialogue-facility-believer-02.mp3",
  "荘厳さと効率。どちらも譲れませんの。": "/assets/audio/voice/dialogue-facility-altar-01.mp3",
  "祭壇のお手入れは、柔らかい布でお願いいたします。": "/assets/audio/voice/dialogue-facility-altar-02.mp3",
  "よくここまで満たしましたわね。見上げてもよろしくてよ。": "/assets/audio/voice/dialogue-facility-giant-statue-01.mp3",
  "像のほうが本人より立派、というご意見は受け付けておりません。": "/assets/audio/voice/dialogue-facility-giant-statue-02.mp3",
  "深夜の一杯には、抗いがたい救済がありますの。": "/assets/audio/voice/dialogue-facility-ramen-sanctum-01.mp3",
  "替え玉は御利益に含まれます。たぶん。": "/assets/audio/voice/dialogue-facility-ramen-sanctum-02.mp3",
  "本日の放送も、内容より雰囲気を重視しております。": "/assets/audio/voice/dialogue-facility-cult-broadcast-01.mp3",
  "こちら満足放送局。受信状態はいかがでしょうか。": "/assets/audio/voice/dialogue-facility-cult-broadcast-02.mp3",
  "仮設支部がずいぶん立派になりましたこと。": "/assets/audio/voice/dialogue-facility-neo-cathedral-01.mp3",
  "大聖堂でも、やることはいつも通りのひとさわりですわ。": "/assets/audio/voice/dialogue-facility-neo-cathedral-02.mp3",
  "向こう側の世界にも、おすそ分けいたしましょう。": "/assets/audio/voice/dialogue-facility-dimension-gate-01.mp3",
  "次元を越えてまで布教するとは、ずいぶん遠くへ来ましたわね。": "/assets/audio/voice/dialogue-facility-dimension-gate-02.mp3",
  "銀河にも満足を。教義は到着までに考えますわ。": "/assets/audio/voice/dialogue-facility-cosmic-chiruko-01.mp3",
  "宇宙船の窓から見る満足も、なかなか壮観ですの。": "/assets/audio/voice/dialogue-facility-cosmic-chiruko-02.mp3",
  "架空の進化も、信じればだいたい満足ですわ。": "/assets/audio/voice/dialogue-facility-sora-3-01.mp3",
  "Sora3が描く未来では、満足が光速を越えるそうですの。": "/assets/audio/voice/dialogue-facility-sora-3-02.mp3",
  "天文台から見る満足の星は、ひとつひとつ違う色に見えるそうですわ。": "/assets/audio/voice/dialogue-facility-satisfaction-observatory-01.mp3",
  "遠くを観測するほど、次に届けたい満足が見つかりますの。": "/assets/audio/voice/dialogue-facility-satisfaction-observatory-02.mp3",
  "艦隊が銀河の向こうまで、満足の便りを運んでいますわ。": "/assets/audio/voice/dialogue-facility-galaxy-mission-fleet-01.mp3",
  "船団の航路が増えるほど、宇宙は少しずつ優しくなりますの。": "/assets/audio/voice/dialogue-facility-galaxy-mission-fleet-02.mp3",
  "宇宙を丸ごとシミュレートして、満足の増え方を予習中ですわ。": "/assets/audio/voice/dialogue-facility-satisfaction-simulator-01.mp3",
  "計算結果はいつも、予想より少しだけ満足寄りですの。": "/assets/audio/voice/dialogue-facility-satisfaction-simulator-02.mp3",
  "赤い雲が怒っているように見えても、夢を出力する準備中ですわ。": "/assets/audio/voice/dialogue-facility-sora-4-01.mp3",
  "Sora4の夢想圏から、まだ名前のない満足が届きましたの。": "/assets/audio/voice/dialogue-facility-sora-4-02.mp3",
  "熱心ですこと。おでこは丁重にお願いいたしますわ。": "/assets/audio/voice/dialogue-condition-clicks-20.mp3",
  "百回も？ その情熱、もはやひとつの教義ですわね。": "/assets/audio/voice/dialogue-condition-clicks-100.mp3",
  "千のひとさわり……おでこが功徳で輝きそうですわ。": "/assets/audio/voice/dialogue-condition-clicks-1000.mp3",
  "何もしない時間にも、満足は育ちますの。": "/assets/audio/voice/dialogue-condition-production-1.mp3",
  "もう手動より設備の皆さまのほうが働いておりますわね。": "/assets/audio/voice/dialogue-condition-production-1000.mp3",
  "一秒ごとの満足が、ちょっとした災害の規模ですわ。": "/assets/audio/voice/dialogue-condition-production-1000000.mp3",
  "ここまで来ると、数字というより景色ですわね。": "/assets/audio/voice/dialogue-condition-total-1b.mp3",
  "奇跡が重なっております！ 理屈はあとで考えましょう！": "/assets/audio/voice/dialogue-condition-buff-combo-01.mp3",
  "コンボ中ですわ。いまは数字だけをご覧なさいませ！": "/assets/audio/voice/dialogue-condition-buff-combo-02.mp3",
  "眠っているように見えて、自動生産は働いておりますの。": "/assets/audio/voice/dialogue-skin-sleep.mp3",
  "教典を読んでおります。まだ白紙のページが多いですわ。": "/assets/audio/voice/dialogue-skin-read.mp3",
  "走っておりますけれど、目的地は特に決めておりません。": "/assets/audio/voice/dialogue-skin-run.mp3",
  "お迎え、ありがとうございますわ。": "/assets/audio/voice/event-purchase.mp3",
  "御利益を授けましょう。": "/assets/audio/voice/event-upgrade.mp3",
  "この教義は、次の世界にも残りますわ。": "/assets/audio/voice/event-doctrine.mp3",
  "もう一度、世界を満たしましょう。": "/assets/audio/voice/event-prestige.mp3",
}

export const getVoiceClipPath = (text: string) => {
  const path = VOICE_CLIP_PATHS[text]
  return path ? assetPath(path) : null
}
